spring:
  application:
    name: shopping_cart

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15mins
    refreshTokenExpiration : 604800 #7days
  profiles:
    active: dev
  stripe:
    secretKey : ${STRIPE_SECRET_KEY}
    webhookSecretKey : ${STRIPE_WEBHOOK_SECRET_KEY}
