spring:
  application:
    name: shopping_cart
  datasource:
    url: jdbc:mysql://localhost:3307/store_2?createDatabaseIfNotExist=true
    username: root
    password: query
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #5min
    refreshTokenExpiration : 604800 #7days